export const MODAL_TEST_SELECTOR = '#modal-test'
export const MODAL_TEST_TEST_SELECTOR = '.modalTest__test'
export const MODAL_TEST_QUESTION_NUMBER_SELECTOR = '.modalTest__test-number'
export const MODAL_TEST_QUESTION_SELECTOR = '.modalTest__test-question'
export const MODAL_TEST_FORM_SELECTOR = '.modalTest__form'
export const MODAL_TEST_PREV_BUTTON_SELECTOR = '[data-modal-test-prev]'
export const MODAL_TEST_NEXT_BUTTON_SELECTOR = '[data-modal-test-next]'
export const MODAL_TEST_PROGRESS_SELECTOR = '.modalTest__progress-current'
export const MODAL_TEST_STEPS_CURRENT_SELECTOR = '[data-modal-test-step-current]'
export const MODAL_TEST_STEPS_TOTAL_SELECTOR = '[data-modal-test-step-all]'
export const MODAL_TEST_STEPS_CIRCLES_SELECTOR = '.modalTest__steps-circles'
export const MODAL_TEST_BUTTONS_SELECTOR = '.modalTest__btns'

export const MODAL_TEST_GOTO_NEXT_EVENT = 'modal-test-goto-next'
export const MODAL_TEST_GOTO_PREV_EVENT = 'modal-test-goto-prev'